[DEFAULT]
# Controls the algorithm's sensitivity by dictating the minimum number of pixels that must be detected in one area as having changed to constitute motion
sensitivity=10000
# Specifies how many frames must be processed before a new reference frame is taken
reference_frame_reset_interval=30
